name: build-app


env:
  CONTAINER_IMAGE_NAME: "app-showcase-frontend-nodejs"
  ARTIFACTORY_NAMESPACE: "com/db/hackerthon"
  ARTIFACTORY_HOST: "artifactory.sdlc.ctl.gcp.db.com/artifactory"
  ARTIFACTORY_BASE_URL: "https://artifactory.sdlc.ctl.gcp.db.com"
  PROJECT_ID: "db-dev-ydjz-gcplabs-lab-17"
  VERSION: "0.0.3"

on:
  push:
    branches:
      - '*'

jobs:

  build:
    name: Build
    runs-on: dbgdbc_docker
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: repo-checkout
        uses: actions/checkout@v2

      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Set up to node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install and Generate Test Report
        env:
          NPM_EMAIL_ID: ${{ steps.secrets.outputs.artifactory_releaser_username }}
          ARTIFACTORY_RELEASER_USERNAME: hackerthon-releaser
          ARTIFACTORY_RELEASER_PASSWORD: AKCp8nGFipQ4MyBoMxRUhUjcqC8v8AiqQppUGARKTpjArak2sbiCnjduA3E2wACibztbkwepZ
        run: |-
          export NPM_AUTH=$(echo -n "${ARTIFACTORY_RELEASER_USERNAME}:${ARTIFACTORY_RELEASER_PASSWORD}" | base64)
          echo "Pankaj"
          pwd
          cd ui
          npm install
      

      - name: Build image with Docker
        env:
          ARTIFACTORY_RELEASER_USERNAME: hackerthon-releaser
          ARTIFACTORY_RELEASER_PASSWORD: AKCp8nGFipQ4MyBoMxRUhUjcqC8v8AiqQppUGARKTpjArak2sbiCnjduA3E2wACibztbkwepZ
          VERSION: ${{ github.sha }}
        run: |-
          RELEASE_VERSION=${GITHUB_REF:10}
          echo "Logging into docker"
          echo ${ARTIFACTORY_RELEASER_PASSWORD} | docker login --password-stdin --username ${ARTIFACTORY_RELEASER_USERNAME}  ${ARTIFACTORY_BASE_URL}/
          echo "Triggering docker build"
          DOCKER_BUILDKIT=1 \
          docker build -t ${ARTIFACTORY_HOST}/dkr-public-local/${ARTIFACTORY_NAMESPACE}/${CONTAINER_IMAGE_NAME}:$VERSION \
            --build-arg ARTIFACTORY_RELEASER_USERNAME="${ARTIFACTORY_RELEASER_USERNAME}" \
            --secret id=artifactory_password,env=ARTIFACTORY_RELEASER_PASSWORD \
            -f Dockerfile .
          echo "Preview images"
          docker images
          echo "Push to artifactory"
          docker push ${ARTIFACTORY_HOST}/dkr-public-local/${ARTIFACTORY_NAMESPACE}/${CONTAINER_IMAGE_NAME}:$VERSION